export const ecommerceDemoSchema = {
  entities: [
    {
      name: "Customers",
      schema: "Demo",
      columns: [
        {
          name: "CustomerID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "FirstName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "LastName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Email",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Phone",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "CreatedDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
    {
      name: "Addresses",
      schema: "Demo",
      columns: [
        {
          name: "AddressID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "CustomerID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "AddressLine1",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "AddressLine2",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "City",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "State",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "PostalCode",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Country",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "IsBillingAddress",
          dataType: "bit",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "IsShippingAddress",
          dataType: "bit",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
    {
      name: "Categories",
      schema: "Demo",
      columns: [
        {
          name: "CategoryID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "CategoryName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Description",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
    {
      name: "Suppliers",
      schema: "Demo",
      columns: [
        {
          name: "SupplierID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "SupplierName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "ContactName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Phone",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Email",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Country",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
    {
      name: "Products",
      schema: "Demo",
      columns: [
        {
          name: "ProductID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "CategoryID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "SupplierID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "ProductName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Description",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Price",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "StockQuantity",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "CreatedDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
    {
      name: "Orders",
      schema: "Demo",
      columns: [
        {
          name: "OrderID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "CustomerID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "ShippingAddressID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "BillingAddressID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "OrderDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "TotalAmount",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
    {
      name: "OrderDetails",
      schema: "Demo",
      columns: [
        {
          name: "OrderDetailID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "OrderID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "ProductID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Quantity",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Price",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
    {
      name: "Payments",
      schema: "Demo",
      columns: [
        {
          name: "PaymentID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          name: "OrderID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "PaymentDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "PaymentMethod",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "PaymentStatus",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          name: "Amount",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
    },
  ],
  relationships: [
    {
      foreignKeyName: "FK__Addresses__Custo__3D5E1FD2",
      schemaName: "Demo",
      entity: "Addresses",
      column: "CustomerID",
      referencedSchema: "Demo",
      referencedEntity: "Customers",
      referencedColumn: "CustomerID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__Orders__Customer__4BAC3F29",
      schemaName: "Demo",
      entity: "Orders",
      column: "CustomerID",
      referencedSchema: "Demo",
      referencedEntity: "Customers",
      referencedColumn: "CustomerID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__Orders__Shipping__4CA06362",
      schemaName: "Demo",
      entity: "Orders",
      column: "ShippingAddressID",
      referencedSchema: "Demo",
      referencedEntity: "Addresses",
      referencedColumn: "AddressID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__Orders__BillingA__4D94879B",
      schemaName: "Demo",
      entity: "Orders",
      column: "BillingAddressID",
      referencedSchema: "Demo",
      referencedEntity: "Addresses",
      referencedColumn: "AddressID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__Products__Catego__46E78A0C",
      schemaName: "Demo",
      entity: "Products",
      column: "CategoryID",
      referencedSchema: "Demo",
      referencedEntity: "Categories",
      referencedColumn: "CategoryID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__Products__Suppli__47DBAE45",
      schemaName: "Demo",
      entity: "Products",
      column: "SupplierID",
      referencedSchema: "Demo",
      referencedEntity: "Suppliers",
      referencedColumn: "SupplierID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__OrderDeta__Produ__52593CB8",
      schemaName: "Demo",
      entity: "OrderDetails",
      column: "ProductID",
      referencedSchema: "Demo",
      referencedEntity: "Products",
      referencedColumn: "ProductID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__OrderDeta__Order__5165187F",
      schemaName: "Demo",
      entity: "OrderDetails",
      column: "OrderID",
      referencedSchema: "Demo",
      referencedEntity: "Orders",
      referencedColumn: "OrderID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
    {
      foreignKeyName: "FK__Payments__OrderI__571DF1D5",
      schemaName: "Demo",
      entity: "Payments",
      column: "OrderID",
      referencedSchema: "Demo",
      referencedEntity: "Orders",
      referencedColumn: "OrderID",
      onDeleteAction: 0,
      onUpdateAction: 0,
    },
  ],
};
