export const ecommerceDemoSchema = {
  tables: [
    {
      id: "fcc48590-4456-4844-a230-7dd6e83f1b79",
      name: "Customers",
      schema: "Demo",
      columns: [
        {
          id: "adfd099d-bb0d-40dc-a548-50c8649566f9",
          name: "CustomerID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "e06b503c-98bc-4113-b8a3-9094f26987e6",
          name: "FirstName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "84eb5fe1-2738-403f-901d-ecd1b5a69858",
          name: "LastName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "4d91ce5b-4b70-4b48-8180-1ebc806382bc",
          name: "Email",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "f6dead34-49ba-4c3f-87e1-f65e7c287136",
          name: "Phone",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "50b2bb2f-3c41-4e4a-9500-0456c8a86400",
          name: "CreatedDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
      ],
    },
    {
      id: "95dc8c57-f710-4ffb-b9bd-c8cfe801091b",
      name: "Addresses",
      schema: "Demo",
      columns: [
        {
          id: "3370fd9e-b680-4556-bf5d-cc8a444b7744",
          name: "AddressID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "dba3932b-6c31-4f6d-93cf-60793a723a32",
          name: "CustomerID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "390569d6-ee83-41e3-917b-0e2972aac369",
          name: "AddressLine1",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "d4bf69a2-b3a1-4aa0-b9f2-1c9a750920d0",
          name: "AddressLine2",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "a1b7711d-b7f0-46c7-aa41-ec9070e94802",
          name: "City",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "18dba408-7514-4227-a04c-61b667334620",
          name: "State",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "56e6077c-5b66-4036-856a-47b2f94e5d6f",
          name: "PostalCode",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "3a0ca457-a0e3-4a6b-b289-a74fce9b2e35",
          name: "Country",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "5cd5fd26-2a60-4131-99ab-d589a1400f5c",
          name: "IsBillingAddress",
          dataType: "bit",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "898e7f78-7e23-4aa4-8aeb-0548505ab14d",
          name: "IsShippingAddress",
          dataType: "bit",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
        {
          id: "47638f9f-de35-4f7a-b10b-a79739d211d7",
          name: "FK__Addresses__Custo__3D5E1FD2",
          columns: [
            "CustomerID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Customers",
          referencedColumns: [
            "CustomerID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
      ],
    },
    {
      id: "007d3d4d-d34c-4aa8-ac0a-789a43434532",
      name: "Categories",
      schema: "Demo",
      columns: [
        {
          id: "0ced6373-d7fb-44b8-a866-7fd190dc83fb",
          name: "CategoryID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "0fb78d8c-a13c-4a46-a0f8-5f8522c214a4",
          name: "CategoryName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "69459ae6-f32e-4223-ac6f-b9afe1421fb9",
          name: "Description",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
      ],
    },
    {
      id: "02d781aa-6b7e-417c-8059-eb97f4d39032",
      name: "Suppliers",
      schema: "Demo",
      columns: [
        {
          id: "5cdc66c4-9e3d-42e2-8ebd-91b99cd973b7",
          name: "SupplierID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "499a9885-5b2a-47e6-8483-9ec5b5258d76",
          name: "SupplierName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "3e4b6940-2800-4804-999e-b27b0b87d526",
          name: "ContactName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "4145ffb9-ecbc-4c68-a0f0-d3d7bafc804f",
          name: "Phone",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "092d8a8f-8371-4f6a-8a18-b55ae3a31567",
          name: "Email",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "cf56d532-bfe7-49b1-9e8c-ca547e55b5f0",
          name: "Country",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
      ],
    },
    {
      id: "5078e86b-364b-435e-a7fa-68ec84d8f82a",
      name: "Products",
      schema: "Demo",
      columns: [
        {
          id: "e3d45670-fdf5-44b9-a9de-fbd4bddf1150",
          name: "ProductID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "9399ce1b-f7a2-4b38-bc82-8ed776790337",
          name: "CategoryID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "e5dabf25-7714-478b-af75-e22f2705d493",
          name: "SupplierID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "934a15eb-688a-4ac2-9ed3-4927d71f89c2",
          name: "ProductName",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "7691c49b-6766-405f-829c-3e8739643fb4",
          name: "Description",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "6a17837b-6481-4c31-9582-98867af44faf",
          name: "Price",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "79e90521-5689-4053-a8f7-b76a6ea97f9c",
          name: "StockQuantity",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "2cb976b4-d24f-47cf-9e7f-0d8b7a8444d7",
          name: "CreatedDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
        {
          id: "3abfff2d-9a56-4248-adcc-33cb679b02a4",
          name: "FK__Products__Catego__46E78A0C",
          columns: [
            "CategoryID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Categories",
          referencedColumns: [
            "CategoryID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
        {
          id: "3399d6b3-add0-43ff-9b53-27bdcbaf6975",
          name: "FK__Products__Suppli__47DBAE45",
          columns: [
            "SupplierID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Suppliers",
          referencedColumns: [
            "SupplierID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
      ],
    },
    {
      id: "40a02d8a-d35a-44ed-a9b2-2e306f57f8fc",
      name: "Orders",
      schema: "Demo",
      columns: [
        {
          id: "3aef1d88-da8e-4f70-a148-a80c61211431",
          name: "OrderID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "f374b461-48ad-4d99-b363-17974837749b",
          name: "CustomerID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "84219333-86c5-415f-b8fe-9436ddede11f",
          name: "ShippingAddressID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "6cc0c453-ae90-41f8-b3c6-72b5e90a55ee",
          name: "BillingAddressID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "4640e5be-5d6d-4449-bc2e-08afc3c32289",
          name: "OrderDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "95fbfcd9-4bac-4325-bde1-263147724deb",
          name: "TotalAmount",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
        {
          id: "4ea95c3f-5574-4671-bd74-768f2f143fe4",
          name: "FK__Orders__BillingA__4D94879B",
          columns: [
            "BillingAddressID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Addresses",
          referencedColumns: [
            "AddressID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
        {
          id: "cab4e31f-7d19-41b6-9983-401957d23d81",
          name: "FK__Orders__Customer__4BAC3F29",
          columns: [
            "CustomerID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Customers",
          referencedColumns: [
            "CustomerID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
        {
          id: "07254e30-fe74-40dc-8d7b-8bd08ac22fbd",
          name: "FK__Orders__Shipping__4CA06362",
          columns: [
            "ShippingAddressID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Addresses",
          referencedColumns: [
            "AddressID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
      ],
    },
    {
      id: "936a92cd-a954-41af-89df-ffbbd14904d6",
      name: "OrderDetails",
      schema: "Demo",
      columns: [
        {
          id: "5532ad2e-0b3c-43b2-bf17-c9de8958afd6",
          name: "OrderDetailID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "2c080b47-65ed-4d4b-aec9-4605f88f2f56",
          name: "OrderID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "a55e5c53-e499-454b-9fc0-42365557aa47",
          name: "ProductID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "0d7e34e5-3b94-47ac-95dd-add3b34ff417",
          name: "Quantity",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "64c09da8-bbd5-4b90-9b55-58b1cb1d4c8d",
          name: "Price",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
        {
          id: "066a233a-2bb3-4f9a-b0c6-974eee80f01f",
          name: "FK__OrderDeta__Order__5165187F",
          columns: [
            "OrderID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Orders",
          referencedColumns: [
            "OrderID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
        {
          id: "560d3ec9-bbe6-496b-aad8-b1dd5a768d7e",
          name: "FK__OrderDeta__Produ__52593CB8",
          columns: [
            "ProductID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Products",
          referencedColumns: [
            "ProductID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
      ],
    },
    {
      id: "c8e6be42-c46d-492c-b065-d8689833e2c4",
      name: "Payments",
      schema: "Demo",
      columns: [
        {
          id: "27593edb-b19d-405b-b19b-c987055b8b4c",
          name: "PaymentID",
          dataType: "int",
          isPrimaryKey: true,
          isIdentity: true,
        },
        {
          id: "7564cd0f-a840-4fdb-bc20-19e1d226a654",
          name: "OrderID",
          dataType: "int",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "b492e6bd-36bb-429f-ac48-e55eb9bbcd94",
          name: "PaymentDate",
          dataType: "datetime",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "f43629a1-9443-4950-9ed3-671f6f5304ae",
          name: "PaymentMethod",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "33f8ae0c-ec58-400f-98fb-cade40a5be6b",
          name: "PaymentStatus",
          dataType: "nvarchar",
          isPrimaryKey: false,
          isIdentity: false,
        },
        {
          id: "d0f4986f-3f94-4947-b765-8d8e946dd906",
          name: "Amount",
          dataType: "decimal",
          isPrimaryKey: false,
          isIdentity: false,
        },
      ],
      foreignKeys: [
        {
          id: "91d01244-0e01-4dfc-a88a-74afb05a9296",
          name: "FK__Payments__OrderI__571DF1D5",
          columns: [
            "OrderID",
          ],
          referencedSchemaName: "Demo",
          referencedTableName: "Orders",
          referencedColumns: [
            "OrderID",
          ],
          onDeleteAction: 0,
          onUpdateAction: 0,
        },
      ],
    },
  ]
};